### ISSUE TITLE
Bipartition is mutable: hash is unstable

### ISSUE THREAD

**Issue by any333** [jeetsukumaran/DendroPy#100]
Hi,

I am currently working with DendroPy and ETE3.
What I am trying to achieve is, by using the two libraries, to compare directories in a file system.
With ETE3 I create tree objects in the newick format, which works totally fine. 
Exporting the strings into DendroPy works good as well.
When I try to compare (with robinson foulds / euclidean distance function, which DendroPy is offering) two trees built out of directories, an runtime error occurs with the following message: 
"**AssertionError, Bipartition is mutable: hash is unstable**"

I tried to fix the problem in many ways, but nothing helped so far. 
How do I get the bipartition of my tree objects set to "is_mutable=False", so they can meet the requirements of the compare function?

**Comment by jeetsukumaran** [comment]
As with most software problems, you will find yourself in a much better position to be helped if you submit at the very, very, very, very, very least:

(1) a minimal code example that replicates the issue
(2) the full error log / stack trace

**Comment by any333** [comment]
Sure,

tree1 and tree2 are coming from the ETE3 Library.
I wrote an algorithm to create a tree out of a directory from my hard drive.
Everything works fine with a small directory, but when the directory is really big I get the following exception in the line where robinson foulds distance is calculated:

Exception has occurred.
AssertionError, Bipartition is mutable: hash is unstable
``
tns = dendropy.TaxonNamespace()
dt1 = dendropy.Tree.get(data=tree1.write(format=1), schema="newick", taxon_namespace=tns, suppress_internal_node_taxa=True, suppress_leaf_node_taxa=True)
dt2 = dendropy.Tree.get(data=tree2.write(format=1), schema="newick", taxon_namespace=tns, suppress_internal_node_taxa=True, suppress_leaf_node_taxa=True)

b1 = dt1.encode_bipartitions()
b2 = dt2.encode_bipartitions()

print(dendropy.calculate.treecompare.robinson_foulds_distance(dt1, dt2))
``


![screengithub](https://user-images.githubusercontent.com/2464874/46215555-f2e02f80-c33d-11e8-8844-e70e9685905c.png)

**Comment by jeetsukumaran** [comment]
(1) Why are you suppressing leaf taxa? This is required to calculate bipartition hashes. This is the cause of your error.

(2) Also note that you are using the deprecated "robinson_foulds_distance()" function which assumes all edges have lengths. You probably want to use "symmetric_difference()"

(3) The "stack trace" that I suggested you include is the full text of the error listing that prints out all line numbers / file names in the execution stack.  This is very important for debugging and error analysis. Your screen shot does not cover this. You might be able to get it if you expand the error window and select all the text there. Please do find this and include this in the future (and this does not just pertain to this software project, but, really, any bug/problem reporting with any software project).

(4) The minimum working example that I suggested you include is what allows me to run the code on my end and replicate the error. Your code fragment does not. It is not sufficient to reference trees from elsewhere that I do not have access to. If necessary, you may need to modify the code so that it does become a standalone replication of your problem as I have done in the example below.

(5) Below is a modified version of your code. The key difference with respected to the reported issue is that the leaf taxa are not suppressed. I also changed the calculation function from ``robinson_foulds_distance()" to "symmetric_difference()" as discussed above.

    #! /usr/bin/env python
    # -*- coding: utf-8 -*-

    import dendropy

    s1 = "[&R] (A, (B, (C,D)));"
    s2 = "[&R] ((A,B),(C,D));"
    tns = dendropy.TaxonNamespace()
    dt1 = dendropy.Tree.get(
            data=s1,
            schema="newick",
            taxon_namespace=tns,
            suppress_internal_node_taxa=True,
            suppress_leaf_node_taxa=False)
    dt2 = dendropy.Tree.get(
            data=s2,
            schema="newick",
            taxon_namespace=tns,
            suppress_internal_node_taxa=True,
            suppress_leaf_node_taxa=False)

    b1 = dt1.encode_bipartitions()
    b2 = dt2.encode_bipartitions()

    print(dendropy.calculate.treecompare.symmetric_difference(dt1, dt2))
