### ISSUE TITLE
please create a release

### ISSUE THREAD

**Issue by joelb123** [jeetsukumaran/DendroPy#137]
Hi, to help with us users keeping up with developments, please create a release as well as update your tags.  pypi lists 4.5.2 as the latest package, but there is no tag for 4.5.2 and no releases for anything.

**Comment by mmore500** [comment]
In case it's still useful to you, I put together a fork on PyPi to host releases tracking the more recent history on the main branch of DendroPy (<https://pypi.org/project/DendroPy-calver/>) as well as some pending PRs. As another alternative, python package management systems can usually pin to specific commits on public git repositories.

**Comment by jeetsukumaran** [comment]
Hi, first of, apologies to @joelb123 for the delay in responding to this.

Secondly, THANK you so much @mmore500 for your help here as well as the other feedback and PR's. Very much appreciated :)

As you can imagine, I'm a bit behind, but will hopefully take care of this in my next work cycle. As @mmore500 suggests, I personally pin to "development-main" or "main" rather than specific releases, but, of course, that's no excuse for not update version numbers.

**Comment by mmore500** [comment]
No worries --- & totally relatable :). Glad to help how I can. If it would be useful to add some infrastructure to make releasing easier to keep up with (github actions CI for tests, a version bumping script, autodeploy on tagged releases via CI), I'd be happy to contribute a PR with some of that.

**Comment by mmore500** [comment]
I'd be open to that! That might actually be helpful for getting the CI running. I'll draft something up and @ you if I run into any issues with permissions as an outside contributor.

**Comment by mmore500** [comment]
Hi @joelb123  --- closing this, as we just deployed a new release (v4.6.0) to PyPi.  We've put together a more streamlined release process, so this will be easier to keep up with in the future.
