### ISSUE TITLE
'Tree' object has no attribute 'bipartitions'

### ISSUE THREAD

**Issue by dparks1134** [jeetsukumaran/DendroPy#31]
Calling ```TreeList.frequency_of_bipartition()``` can fail as the ```bipartitions``` attribute is not defined for ```Tree``` objects. Perhaps this is suppose to be ```bipartition_encoding```?

```
File "/srv/sw/DendroPy/4.0.3/lib/python2.7/site-packages/dendropy/datamodel/treecollectionmodel.py", line 1197, in frequency_of_bipartition
    if not is_bipartitions_updated or not tree.bipartitions:
AttributeError: 'Tree' object has no attribute 'bipartitions'
```

**Comment by jeetsukumaran** [comment]
You are absolutely correct: it is supposed to be `bipartition_encoding`.

This has been fixed in: 9775034 .

A test has been added to guard against the case that you describe:

	https://github.com/jeetsukumaran/DendroPy/blob/development-master/dendropy/test/test_tree_calculations_and_metrics.py#L1138-L1146

Thanks for pointing this issue out!

-- jeet

On 9/7/15 10:13 PM, Donovan Parks wrote:
> Calling |TreeList.frequency_of_bipartition()| can fail as the
> |bipartitions| attribute is not defined for |Tree| objects. Perhaps this
> is suppose to be |bipartition_encoding|?
>
> |File
> "/srv/sw/DendroPy/4.0.3/lib/python2.7/site-packages/dendropy/datamodel/treecollectionmodel.py",
> line 1197, in frequency_of_bipartition if not is_bipartitions_updated or
> not tree.bipartitions: AttributeError: 'Tree' object has no attribute
> 'bipartitions' |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeetsukumaran/DendroPy/issues/31>.
>

-- 



--------------------------------------
Jeet Sukumaran
--------------------------------------
jeetsukumaran@gmail.com
--------------------------------------
Blog/Personal Pages:
    http://jeetworks.org/
GitHub Repositories:
    http://github.com/jeetsukumaran
Photographs (as stream):
    http://www.flickr.com/photos/jeetsukumaran/
Photographs (by galleries):
    http://www.flickr.com/photos/jeetsukumaran/sets/
--------------------------------------
