### ISSUE TITLE
Inconsistent AttributeError on deepcopy

### ISSUE THREAD

**Issue by biologyguy** [jeetsukumaran/DendroPy#35]
Hi there,
I've been getting an intermittent error that you might be interested in. 

```
PhyloBuddy.py:408: in _make_copy
    return deepcopy(_phylobuddy)
../../../anaconda/lib/python3.4/copy.py:182: in deepcopy
    y = _reconstruct(x, rv, 1, memo)
../../../anaconda/lib/python3.4/copy.py:300: in _reconstruct
    state = deepcopy(state, memo)
../../../anaconda/lib/python3.4/copy.py:155: in deepcopy
    y = copier(x, memo)
../../../anaconda/lib/python3.4/copy.py:246: in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
../../../anaconda/lib/python3.4/copy.py:155: in deepcopy
    y = copier(x, memo)
../../../anaconda/lib/python3.4/copy.py:219: in _deepcopy_list
    y.append(deepcopy(a, memo))
../../../anaconda/lib/python3.4/copy.py:166: in deepcopy
    y = copier(memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/treemodel.py:3117: in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/basemodel.py:785: in __deepcopy__
    other.__dict__[k] = copy.deepcopy(self.__dict__[k], memo)
../../../anaconda/lib/python3.4/copy.py:166: in deepcopy
    y = copier(memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/treemodel.py:1006: in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/basemodel.py:785: in __deepcopy__
    other.__dict__[k] = copy.deepcopy(self.__dict__[k], memo)
../../../anaconda/lib/python3.4/copy.py:155: in deepcopy
    y = copier(x, memo)
../../../anaconda/lib/python3.4/copy.py:219: in _deepcopy_list
    y.append(deepcopy(a, memo))
../../../anaconda/lib/python3.4/copy.py:166: in deepcopy
    y = copier(memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/treemodel.py:1006: in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/basemodel.py:785: in __deepcopy__
    other.__dict__[k] = copy.deepcopy(self.__dict__[k], memo)
../../../anaconda/lib/python3.4/copy.py:155: in deepcopy
    y = copier(x, memo)
../../../anaconda/lib/python3.4/copy.py:219: in _deepcopy_list
    y.append(deepcopy(a, memo))
../../../anaconda/lib/python3.4/copy.py:166: in deepcopy
    y = copier(memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/treemodel.py:1006: in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/basemodel.py:785: in __deepcopy__
    other.__dict__[k] = copy.deepcopy(self.__dict__[k], memo)
../../../anaconda/lib/python3.4/copy.py:155: in deepcopy
    y = copier(x, memo)
../../../anaconda/lib/python3.4/copy.py:219: in _deepcopy_list
    y.append(deepcopy(a, memo))
../../../anaconda/lib/python3.4/copy.py:166: in deepcopy
    y = copier(memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/treemodel.py:1006: in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/basemodel.py:785: in __deepcopy__
    other.__dict__[k] = copy.deepcopy(self.__dict__[k], memo)
../../../anaconda/lib/python3.4/copy.py:155: in deepcopy
    y = copier(x, memo)
../../../anaconda/lib/python3.4/copy.py:219: in _deepcopy_list
    y.append(deepcopy(a, memo))
../../../anaconda/lib/python3.4/copy.py:166: in deepcopy
    y = copier(memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/treemodel.py:1006: in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/basemodel.py:785: in __deepcopy__
    other.__dict__[k] = copy.deepcopy(self.__dict__[k], memo)
../../../anaconda/lib/python3.4/copy.py:166: in deepcopy
    y = copier(memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/treemodel.py:759: in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/basemodel.py:789: in __deepcopy__
    other.deep_copy_annotations_from(self, memo)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <dendropy.datamodel.treemodel.Edge object at 0x10b9be128>
other = <dendropy.datamodel.treemodel.Edge object at 0x10b93ba90>
memo = {4297067376: None, 4489007632: 1.0, 4489196880: <PhyloBuddy.PhyloBuddy object at 0x10c074f98>, 4489197608: <Tree object at 0x10c074198>, ...}

    def deep_copy_annotations_from(self, other, memo=None):
        """
            Note that all references to ``other`` in any annotation value (and
            sub-annotation, and sub-sub-sub-annotation, etc.) will be
            replaced with references to ``self``. This may not always make sense
            (i.e., a reference to a particular entity may be absolute regardless of
            context).
            """
        if hasattr(other, "_annotations"):
            # if not isinstance(self, other.__class__) or not isinstance(other, self.__class__):
            if type(self) is not type(other):
                raise TypeError("Cannot deep-copy annotations from different type (unable to assume object equivalence in dynamic or nested annotations)")
            if memo is None:
                memo = {}
            for a1 in other._annotations:
                a2 = copy.deepcopy(a1, memo=memo)
                memo[id(a1)] = a2
                if a2.is_attribute and a1._value[0] is other:
                    a2._value = (self, a1._value[1])
                self.annotations.add(a2)
>           memo[id(other._annotations)] = self._annotations
E           AttributeError: 'Edge' object has no attribute '_annotations'

../../../anaconda/lib/python3.4/site-packages/dendropy/datamodel/basemodel.py:736: AttributeError
```
I'm making a bunch of calls to my _make_copy() function during unit testing, and I'd estimate that the deepcopy() fails with an AttributeError about 30% of the time (seemingly randomly). I haven't really dug into it myself yet, so there could well be a weakness in my own code, but I wanted to pass the traceback along to put it on your radar.
Cheers,
-Steve

**Comment by biologyguy** [comment]
And of course I fix my own issue 10 minutes after sending the traceback... I was inadvertently modifying the DendroPy objects.
Regardless, in the event that an Edge object doesn't have an _annotations attribute, is halt and catch fire the desired behavior, or should this be caught and handled within DendroPy?

**Comment by jeetsukumaran** [comment]
Hi Steve,

Do I feel that non-compatible/unexpected client-code modification (presumably deletion) of a fundamental attribute, explicitly marked by standard Python convention of the leading underscore as "do not touch", of a member of the core data model as provided by DendroPy should be caught and handled by DendroPy? 

No.

No more than we should check if "float()" or "str" has been deleted or otherwise modified/redefined in a breaking/incompatible/unexpected way by the user. Or, indeed, any of the other hundreds or thousands of elements, either as defined by DendroPy, or defined by the Python standard library or as a built-in. That would be thousands of thousands of lines of code just to check to see if that everything we wrote or Python provides has not been incorrectly modified by client code. 

Python allows for great power if modification of the ecosystem. With great power comes great responsibility. We can only assume/hope that if client code modifies anything defined by DendroPy, or, indeed, Python, they do so with the full understanding and knowledge of what they are doing and they maintain compatibility with what DendroPy or Python user expects.

**Comment by biologyguy** [comment]
I'm not hacking on protected attributes and then getting all confused because stuff is blowing up, but I suppose I deserved that. Touché.  I'll be a little more clear about what I've done in the future.

Anyway, for the record, I did spend some more time digging and it looks to me like the override of deepcopy is the source of the issue, although I'm not sure why; I haven't been able to nail down a case that will consistently fail, and the only time exceptions seem to be raised is when I'm running through my unit tests. Given that my code isn't touching yours through protected attributes, I think that there might be some collision happening between dendropy and py.test. I was able to work around the problem, and I might be so far in the weeds that it doesn't matter, but I wanted to at least draw your attention to a possible issue in case it comes up again in the future.

Best,
-Steve

**Comment by jeetsukumaran** [comment]
Hi Steve,

The annotation infrastructure --- which allows for annotation sets to contain not only other annotation objects and annotation set object, but also other objects with their own annotation sets --- makes copying a very complicated operation. It is easily one of the more annoying parts of the data model to work with from this respect. Due to this, against all my coding preferences and instincts, the current native DendroPy data object copy logic is convoluted and fragile. It works, and it works well, AFAIK, but it is not a creature of beauty. 

It is thus no surprise that this nexus (the annotations infrastructure + copying) was the point of failure in your code. I can only apologize for the complexity and fragility in this regard. Perhaps if you describe what you are trying to do with the override of the deepcopy, I might be able to provide some suggestions that might help. And maybe even look into working in logic in the native deepcopy that will prove robust to whatever you are doing at a higher level?

And, for the record, I truly appreciate you pointing it out problems with the library, whether or not the root cause is client code or library code. The bulk of my response above was in response to the suggestion that the library code should check to see if the core data structures had been changed/modified in a non-compatible way. This, I think, is both practically and conceptually unreasonable.

**Comment by biologyguy** [comment]
Cool beans, and no hard feelings. I totally get your point.
As for trying to solve my deepcopy issues, I think it's best to just gently place another layer on the pile and tiptoe away (which I've done). I'm sure we'd both rather focus brain power on the bioinformatics ;)
-Steve
