### ISSUE TITLE
Tests not included in pypi release

### ISSUE THREAD

**Issue by wwood** [jeetsukumaran/DendroPy#96]
Hi,

It seems the tests are not distributed as of 4.4.0. They have been in the past, I believe. Was there some reason to change this?

Thanks, ben

**Comment by jeetsukumaran** [comment]
Hi Ben,

They have been moved but are retained in the repository and distribution.

Where they used to be in "$DENDROPY/dendropy/tests", they are now in "$DENDROPY/tests".
This is along with reorganizing the rest of the project layout, including move the main source from "$DENDROPY/dendropy" to "$DENDROPY/src/dendropy".

For rationale/motivation behind this, see: https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure

**Comment by wwood** [comment]
Hi, just double checked and there is nothing in `tests/` in the tarball on pypi (though there is data):
```
$ tar tf DendroPy-4.4.0.tar.gz |grep tests |grep -v data
DendroPy-4.4.0/tests/
```
I see they are on github there though.

**Comment by jeetsukumaran** [comment]
Ah yes, when I said that tests are in the "distribution", I did not mean PyPi, but if you download a snapshot release. Under this new layout, tests are not part of the end-user code. You will need to checkout the repo (or, less practically, download and install snapshot) for the tests. This is By Design.

**Comment by wwood** [comment]
OK, so the intention then is that the end user shouldn't check that dendropy works as part of their setup. Not sure I agree that's optimal, but OK.

Do you imagine there is any reason I cannot substitute the auto-generated tarball at https://github.com/jeetsukumaran/DendroPy/archive/v4.4.0.tar.gz for the PyPI release, if I wanted to run the tests? From memory this isn't a perfect solution because GitHub does not guarantee that those files do not change i.e. we cannot be sure the sha256 hash of them does not change over time.

Thanks.

**Comment by jeetsukumaran** [comment]
The intention is that for end users who do not want or need to check that dendropy works as part of the setup should not be forced to donwload ~74MB (at time of writing) test code and data to run ~8MB (at time of writing) of library code.

Users who *do* want to test their setup (and it is always nice to have more of them) should download the test code by checking out the repo or downloading the snapshot and run them. I am under the impression that the tests can be run using an existing installation of DendroPy without installing the code that comes with the tests. That is, you can download the repo to some other location and run them there without installing the repo code. So, for example, assuming that you have previously:

```
pip install dendropy
```
you should then be able to:

```
mkdir -p ~/src/dendropy/
cd ~/src/dendropy
git clone https://github.com/jeetsukumaran/DendroPy
cd DendroPy/tests
for t in test_*; do python $t; done
```
Of course if the tests were written against a different version of the installed code, there is a chance that they may fail.

I do not understand what you mean about the hash changing or why that should matter.

However, I do recognize that the above solution to running the tests is not ideal due to the possibility of the non-correspondence between the installed library and the test library. If this is what you mean, then best solution would be to clone the repo and install DendroPy from there:

```
git clone https://github.com/jeetsukumaran/DendroPy
cd DendroPy
pip install -e . # (or: python setup.py develop)
python setup.py test
```

If the above is non-desirable or not possible, then at least you know the first approach will fail conservatively, i.e., if your library is not compatible with the tests, the tests will fail.

**Comment by wwood** [comment]
Hi. OK. Apologies for inducing you to spend so much time on a clear response.

To clear one thing up, hashes of the infamous auto-generated zip and tar.gz files GitHub generates have on occasion changed at least once i.e. contents are unchanged but bit-wise the archives are different. But anyway, it is possible to get around that by sourcing with git rather than fetching the archive.
